version: '2'
services:
  fpy-watchdog:
    container_name: fpy-watchdog
    restart: always
    build:
      context: ./EOL-watchdog
      dockerfile: dockerfile
    stdin_open: true
    tty: true
    volumes:
      - /home/sram-prod/test_results:/eol_test_results

  fpy-watchdog-db:
    image: mongo
    container_name: fpy-watchdog-db
    restart: always
    ports:
      - "27018:27017" # MongoDB default port
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: sramsram-admin
    volumes:
      - mongodb_data:/data/db

  fpy-db-scaner:
    container_name: fpy-db-scaner
    restart: always
    build:
      context: ./db-scaner
      dockerfile: dockerfile
    stdin_open: true
    tty: true
    environment:
      - REMOTE_HOST=10.3.134.87
      - REMOTE_HOST_PORT=9096

volumes:
  mongodb_data:
